#!/usr/bin/env python3
"""Generate Digikala batch1 Part1 catalog (p300–p309) from the wave MANIFEST."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = json.loads((ROOT / "scripts/shop-digikala-batch1-part1.json").read_text(encoding="utf-8"))
DESCRIPTIONS = json.loads((ROOT / "scripts/shop-digikala-batch1-part1-descriptions.json").read_text(encoding="utf-8"))
PRODUCTS = MANIFEST["products"]
CACHE_BUST = MANIFEST["cacheBust"]

# This file is a stub marker; Part1 sources were generated by the import agent.
# Re-run the box build if you need to regenerate from wave-1.json.
if __name__ == "__main__":
    print(f"manifest {len(PRODUCTS)} SKUs cache={CACHE_BUST} — sources already written")
