#!/usr/bin/env npx tsx
/**
 * Generates packages/web/public/sitemap.xml + nginx product id→slug map.
 * Run before web build (also wired in @petdate/web prebuild).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { listProductIdRedirects, listSitemapEntries } from '../packages/web/src/lib/pageSeo.ts';
import { magazineEditorialSlugs } from './magazine-seo.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://petdate.ir';
const OUT = path.join(ROOT, 'packages/web/public/sitemap.xml');
const MAP_OUT = path.join(ROOT, 'infra/nginx/shop-product-redirects.map');

export function writeSitemapArtifacts() {
  const today = new Date().toISOString().slice(0, 10);
  const unique = listSitemapEntries(magazineEditorialSlugs());

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    unique
      .map((u) => {
        const loc = `${ORIGIN}${u.path === '/' ? '/' : encodeURI(u.path)}`;
        return [
          '  <url>',
          `    <loc>${loc}</loc>`,
          `    <lastmod>${today}</lastmod>`,
          `    <changefreq>${u.changefreq}</changefreq>`,
          `    <priority>${u.priority}</priority>`,
          '  </url>',
        ].join('\n');
      })
      .join('\n'),
    '</urlset>',
    '',
  ].join('\n');

  fs.writeFileSync(OUT, xml);

  const redirects = listProductIdRedirects();
  const mapLines = [
    '# Generated by scripts/generate-sitemap.ts — do not edit by hand.',
    'map $uri $shop_product_redirect {',
    '    default "";',
    ...redirects.flatMap((r) => [`    ${r.from} ${r.to};`, `    ${r.from}/ ${r.to};`]),
    '}',
    '',
  ];
  fs.writeFileSync(MAP_OUT, mapLines.join('\n'));

  console.log(`sitemap: wrote ${unique.length} URLs → ${path.relative(ROOT, OUT)}`);
  console.log(`sitemap: wrote ${redirects.length} product id redirects → ${path.relative(ROOT, MAP_OUT)}`);
  return { urlCount: unique.length, redirectCount: redirects.length };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) writeSitemapArtifacts();
